#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: sample-app2-pv
# namespace: ezzatelshazly  
#spec:
#  capacity:
#    storage: 1Gi  
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /home/ezzatelshazly/openshift 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-app2-pvc
  namespace: ezzatelshazly  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: my-ebs
